import { app, BrowserWindow } from 'electron';
import path from 'path'
import {spawn, ChildProcess} from 'child_process'
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

let backendProcess: ChildProcess | null = null;
let isDev = false

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

const getBackendPath = (): string => {
  isDev = process.env.NODE_ENV === 'development' || !app.isPackaged;

  if (isDev) {
    // Development: use local backend
    return path.join(__dirname, '..', '..', 'backend', 'aurelius-backend');
  } else {
    // Production: backend is in resources
    if (process.platform === 'darwin') {
      return path.join(process.resourcesPath, 'backend', 'aurelius-backend');
    } else if (process.platform === 'win32') {
      return path.join(process.resourcesPath, 'backend', 'aurelius-backend.exe');
    }
    throw new Error('Unsupported platform');
  }
}


const startBackend = () => {

  const backendPath = getBackendPath()

  backendProcess = spawn(backendPath, [], {
    stdio:'pipe'
  })

  backendProcess.stdout?.on('data', (data) => {
    console.log(`Backend stdout: ${data}`);
  });

  backendProcess.stderr?.on('data', (data) => {
    console.error(`Backend stderr: ${data}`);
  });

  backendProcess.on('error', (error) => {
    console.error('Failed to start backend:', error);
  });

  backendProcess.on('close', (code) => {
    console.log(`Backend process exited with code ${code}`);
    backendProcess = null;
  });

}

const stopBackend = (): void => {
  if (backendProcess) {
    console.log('Stopping backend process...');
    backendProcess.kill();
    backendProcess = null;
  }
};


const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 600,
    width: 800,
    icon: path.join(__dirname, '../build/icon.png'),
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      devTools:isDev
    }
  });
  mainWindow.webContents.session.webRequest.onHeadersReceived((details, callback) => {
    callback({
      responseHeaders: {
        ...details.responseHeaders,
        'Content-Security-Policy': [
          "default-src 'self'; " +
          "script-src 'self' 'unsafe-eval'; " +
          "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com ; " +
          "font-src 'self' https://fonts.gstatic.com; " +
          "connect-src 'self' ws://localhost:8000 ws://localhost:3000 ws://0.0.0.0:8223 wss://localhost:8000 http://localhost:3000 http://0.0.0.0:8223 http://localhost:8000 http://0.0.0.0:8223"
        ]
      }
    });
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools (only on dev)

  if(isDev){
    mainWindow.webContents.openDevTools();
  }

};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', ()=>{
  startBackend()

  setTimeout(createWindow, 2000)
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  stopBackend()
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

app.on('before-quit', () => {
  stopBackend();
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
